"""Initial database schema with YouTube channel fields and favorites

Revision ID: 79b4815371be
Revises: 
Create Date: 2025-09-15 10:04:04.406934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b4815371be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('explicit_content', sa.Boolean(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('feed_url', sa.String(length=500), nullable=True),
    sa.Column('feed_last_updated', sa.DateTime(), nullable=True),
    sa.Column('feed_validation_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=1000), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('youtube_channel', sa.String(length=255), nullable=True),
    sa.Column('youtube_channel_id', sa.String(length=255), nullable=True),
    sa.Column('youtube_channel_url', sa.String(length=500), nullable=True),
    sa.Column('is_favorited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_episode_channel_status', 'episodes', ['channel_id', 'status'], unique=False)
    op.create_index('idx_episode_channel_video', 'episodes', ['channel_id', 'video_id'], unique=True)
    op.create_index('idx_episode_created_at', 'episodes', ['created_at'], unique=False)
    op.create_index('idx_episode_download_date', 'episodes', ['download_date'], unique=False)
    op.create_index('idx_episode_favorited_channel', 'episodes', ['channel_id', 'is_favorited'], unique=False)
    op.create_index('idx_episode_is_favorited', 'episodes', ['is_favorited'], unique=False)
    op.create_index('idx_episode_publication_date', 'episodes', ['publication_date'], unique=False)
    op.create_index('idx_episode_status', 'episodes', ['status'], unique=False)
    op.create_index('idx_episode_youtube_channel_id', 'episodes', ['youtube_channel_id'], unique=False)
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    op.create_index(op.f('ix_episodes_is_favorited'), 'episodes', ['is_favorited'], unique=False)
    op.create_index(op.f('ix_episodes_status'), 'episodes', ['status'], unique=False)
    op.create_index(op.f('ix_episodes_video_id'), 'episodes', ['video_id'], unique=False)
    op.create_index(op.f('ix_episodes_youtube_channel_id'), 'episodes', ['youtube_channel_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_system_tag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tag_channel', 'tags', ['channel_id'], unique=False)
    op.create_index('idx_tag_channel_name', 'tags', ['channel_id', 'name'], unique=True)
    op.create_index('idx_tag_created_at', 'tags', ['created_at'], unique=False)
    op.create_index('idx_tag_name', 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('episode_tags',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('episode_id', 'tag_id')
    )
    op.create_index('idx_episode_tags_created', 'episode_tags', ['created_at'], unique=False)
    op.create_index('idx_episode_tags_episode', 'episode_tags', ['episode_id'], unique=False)
    op.create_index('idx_episode_tags_tag', 'episode_tags', ['tag_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_channel_created', 'events', ['channel_id', 'created_at'], unique=False)
    op.create_index('idx_event_channel_type_status', 'events', ['channel_id', 'event_type', 'status'], unique=False)
    op.create_index('idx_event_cleanup', 'events', ['created_at', 'severity'], unique=False)
    op.create_index('idx_event_duration', 'events', ['duration_ms'], unique=False)
    op.create_index('idx_event_performance', 'events', ['event_type', 'duration_ms', 'created_at'], unique=False)
    op.create_index('idx_event_resource', 'events', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_event_severity_created', 'events', ['severity', 'created_at'], unique=False)
    op.create_index('idx_event_status_created', 'events', ['status', 'created_at'], unique=False)
    op.create_index('idx_event_type_severity', 'events', ['event_type', 'severity', 'created_at'], unique=False)
    op.create_index('idx_event_user_created', 'events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index('idx_event_user_created', table_name='events')
    op.drop_index('idx_event_type_severity', table_name='events')
    op.drop_index('idx_event_status_created', table_name='events')
    op.drop_index('idx_event_severity_created', table_name='events')
    op.drop_index('idx_event_resource', table_name='events')
    op.drop_index('idx_event_performance', table_name='events')
    op.drop_index('idx_event_duration', table_name='events')
    op.drop_index('idx_event_cleanup', table_name='events')
    op.drop_index('idx_event_channel_type_status', table_name='events')
    op.drop_index('idx_event_channel_created', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_episode_tags_tag', table_name='episode_tags')
    op.drop_index('idx_episode_tags_episode', table_name='episode_tags')
    op.drop_index('idx_episode_tags_created', table_name='episode_tags')
    op.drop_table('episode_tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('idx_tag_name', table_name='tags')
    op.drop_index('idx_tag_created_at', table_name='tags')
    op.drop_index('idx_tag_channel_name', table_name='tags')
    op.drop_index('idx_tag_channel', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_episodes_youtube_channel_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_video_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_status'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_is_favorited'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_index('idx_episode_youtube_channel_id', table_name='episodes')
    op.drop_index('idx_episode_status', table_name='episodes')
    op.drop_index('idx_episode_publication_date', table_name='episodes')
    op.drop_index('idx_episode_is_favorited', table_name='episodes')
    op.drop_index('idx_episode_favorited_channel', table_name='episodes')
    op.drop_index('idx_episode_download_date', table_name='episodes')
    op.drop_index('idx_episode_created_at', table_name='episodes')
    op.drop_index('idx_episode_channel_video', table_name='episodes')
    op.drop_index('idx_episode_channel_status', table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
